version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    groups:
      compose-kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "com.google.devtools.ksp"
