version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: ["fibelatti"]

  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    assignees: ["fibelatti"]
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlinx:*"
          - "io.ktor:*"
          - "com.google.devtools.ksp"
