kotlin.collections.*
kotlin.reflect.KClass
java.io.File
java.util.regex.Pattern
com.fibelatti.core.functional.Either
com.fibelatti.core.functional.Either.Left
com.fibelatti.core.functional.Either.Right
