[versions]
activity = "1.7.1"
agp = "8.0.0"
composeUi = "1.4.3"
coroutines = "1.7.1"
hilt = "2.45"
kotlin = "1.8.21"
lifecycle = "2.6.1"
moshi = "1.15.0"
okhttp = "4.11.0"
retrofit = "2.9.0"
room = "2.5.1"
junit5 = "5.9.3"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.10.1" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.5.7" }
material = { module = "com.google.android.material:material", version = "1.9.0" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
constraint-layout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.1" }
swipe-refresh-layout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }
lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
room-runtime = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version = "2.8.1" }
browser = { module = "androidx.browser:browser", version = "1.5.0" }
viewbinding = { module = "androidx.databinding:viewbinding", version.ref = "agp" }

compose-runtime = { module = "androidx.compose.runtime:runtime", version = "1.4.3" }
compose-material = { module = "androidx.compose.material:material", version = "1.4.3" }
compose-material3 = { module = "androidx.compose.material3:material3", version = "1.1.0" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

jsoup = { module = "org.jsoup:jsoup", version = "1.16.1" }
play-core = { module = "com.google.android.play:core", version = "1.10.3" }
play-core-ktx = { module = "com.google.android.play:core-ktx", version = "1.8.1" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.11" }

junit = { module = "junit:junit", version = "4.13.2" }

junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }

runner = { module = "androidx.test:runner", version = "1.5.2" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
mockk = { module = "io.mockk:mockk", version = "1.13.5" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version = "2.2.0" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.8.21-1.0.11" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
spotless = { id = "com.diffplug.spotless", version = "6.18.0" }
cache-fix = { id = "org.gradle.android.cache-fix", version = "2.7.1" }
