[versions]
activity = "1.8.2"
agp = "8.2.1"
composeCompiler = "1.5.8"
composeBom = "2023.10.01"
coroutines = "1.7.3"
hilt = "2.50"
kotlin = "1.9.22"
lifecycle = "2.7.0"
moshi = "1.15.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
room = "2.6.1"
aboutLibraries = "10.10.0"
junit5 = "5.10.1"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.6.2" }
material = { module = "com.google.android.material:material", version = "1.11.0" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
constraint-layout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.0.1" }
lifecycle-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
room-runtime = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version = "2.9.0" }
browser = { module = "androidx.browser:browser", version = "1.7.0" }
viewbinding = { module = "androidx.databinding:viewbinding", version.ref = "agp" }
window = { module = "androidx.window:window", version = "1.2.0" }

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.1.0" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

jsoup = { module = "org.jsoup:jsoup", version = "1.17.2" }

about-libraries = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutLibraries" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.13" }

junit = { module = "junit:junit", version = "4.13.2" }

junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }

runner = { module = "androidx.test:runner", version = "1.5.2" }
orchestrator = { module = "androidx.test:orchestrator", version = "1.4.2" }

truth = { module = "com.google.truth:truth", version = "1.3.0" }
mockk = { module = "io.mockk:mockk", version = "1.13.9" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version = "2.2.0" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "4.12.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.9.22-1.0.17" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
room = { id = "androidx.room", version.ref = "room" }
spotless = { id = "com.diffplug.spotless", version = "6.24.0" }
cache-fix = { id = "org.gradle.android.cache-fix", version = "3.0" }
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
