name: "Setup Android Build"
description: "Common steps before running a Gradle command"

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.3.3

    - name: Optimize for Gradle build
      shell: bash
      run: |
        mkdir -p ~/.gradle
        cp .github/ci-gradle.properties ~/.gradle/gradle.properties
